{{- if .Values.wordpress.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" . }}
  labels:
{{ include "wordpress.labels" . | nindent 4 }}
{{- end -}}